# 任务配置文件
# 自动生成于: 2026-03-09T12:15:36.476937

# 任务基本信息
task.id=d2d2aa87-bbd5-432e-a62b-eb356fe5e730
task.name=31
task.user.id=1
task.created.at=
task.message.type=TASK_CREATED

# 数据库连接信息
source.connection=mysql://root:rootpassword@192.168.107.6
target.connection=mysql://root:rootpassword@192.168.107.7
