# 任务配置文件
# 自动生成于: 2026-03-09T12:15:36.478251

# 任务基本信息
task.id=73c99a43-a6bf-460b-a84a-15ae8f1e80a9
task.name=33
task.user.id=1
task.created.at=
task.message.type=TASK_CREATED

# 数据库连接信息
source.connection=mysql://root:rootpassword@192.168.107.6
target.connection=mysql://root:rootpassword@192.168.107.7
