#Updated by Migration Agent for task: 7e316f5b-4d4e-4f16-8049-36b19ec9bc35
#Wed Mar 04 14:18:58 CST 2026
migration.batch.size=1000
migration.continue.on.error=false
migration.create.tables=true
migration.drop.tables=false
migration.enable.resume=true
migration.included.databases=myapp_db
migration.included.tables=myapp_db.test1
migration.migrate.data=true
source.db.database=myapp_db
source.db.host=192.168.107.6
source.db.password=rootpassword
source.db.port=3306
source.db.username=root
target.db.database=myapp_db
target.db.host=192.168.107.7
target.db.password=rootpassword
target.db.port=3306
target.db.username=root
