# 任务配置文件
# 自动生成于: 2026-03-11T10:52:00.307218

# 任务基本信息
task.id=1b6f80d9-b89f-4b74-ab00-bf8bc61b4397
task.name=34
task.user.id=1
task.created.at=
task.message.type=TASK_CREATED

# 数据库连接信息
source.connection=mysql://root:rootpassword@192.168.107.6
target.connection=mysql://root:rootpassword@192.168.107.7
