# 任务配置文件
# 自动生成于: 2026-03-11T10:52:00.301977

# 任务基本信息
task.id=7e316f5b-4d4e-4f16-8049-36b19ec9bc35
task.name=23
task.user.id=1
task.created.at=
task.message.type=TASK_CREATED

# 数据库连接信息
source.connection=mysql://root:password@192.168.107.6
target.connection=mysql://root:password@192.168.107.7
