# 任务配置文件
# 自动生成于: 2026-03-05T22:25:57.015669

# 任务基本信息
task.id=e9b93ecd-185a-48e1-87b4-45f1312a11f9
task.name=22
task.user.id=1
task.created.at=
task.message.type=TASK_CREATED

# 数据库连接信息
source.connection=mysql://root:password@192.168.107.6
target.connection=mysql://root:password@192.168.107.7
