# 任务配置文件
# 自动生成于: 2026-03-09T12:15:36.472782

# 任务基本信息
task.id=b5b26efb-7e85-42f5-8e10-e760dc6e62db
task.name=24
task.user.id=1
task.created.at=
task.message.type=TASK_CREATED

# 数据库连接信息
source.connection=mysql://root:password@192.168.107.6/myapp_db
target.connection=mysql://root:password@192.168.107.5/myapp_db
