#Updated by Migration Agent for task: 4c05a40a-cf82-4469-be11-e4cec71d8d87
#Sat Mar 07 10:23:48 CST 2026
source.db.database=myapp_db
source.db.host=192.168.107.6
source.db.password=rootpassword
source.db.port=3306
source.db.username=root
target.db.database=myapp_db
target.db.host=192.168.107.7
target.db.password=rootpassword
target.db.port=3306
target.db.username=root
