# 任务配置文件
# 自动生成于: 2026-03-09T12:15:36.469103

# 任务基本信息
task.id=3f05d564-c636-4403-9997-d0f4657953db
task.name=21
task.user.id=1
task.created.at=
task.message.type=TASK_CREATED

# 数据库连接信息
source.connection=mysql://root:password@192.168.107.6
target.connection=mysql://root:password@192.168.107.7
