# 任务配置文件
# 自动生成于: 2026-03-05T22:25:57.019209

# 任务基本信息
task.id=d4a9e5e4-284f-4863-805b-caa6a77cff4a
task.name=25
task.user.id=1
task.created.at=
task.message.type=TASK_CREATED

# 数据库连接信息
source.connection=mysql://root:password@192.168.107.6
target.connection=mysql://root:password@192.168.107.5
