#Updated by Migration Agent for task: 50598982-fc16-493b-98f5-c442d314b1dd
#Mon Mar 09 12:16:07 CST 2026
source.db.database=myapp_db
source.db.host=192.168.107.6
source.db.password=rootpassword
source.db.port=3306
source.db.username=root
target.db.database=myapp_db
target.db.host=192.168.107.2
target.db.password=rootpassword
target.db.port=3306
target.db.username=root
