# 任务配置文件
# 自动生成于: 2026-03-11T10:52:00.304989

# 任务基本信息
task.id=d89c6539-4ae4-475d-b32f-738305414562
task.name=30
task.user.id=1
task.created.at=
task.message.type=TASK_CREATED

# 数据库连接信息
source.connection=mysql://root:rootpassword@192.168.107.6
target.connection=mysql://root:rootpassword@192.168.107.7
